### ISSUE TITLE
FrameRateConverter.avsi shows incorrect date

### ISSUE THREAD

**Issue by ghost** [mysteryx93/FrameRateConverter#1]
From 1.2.1: 

> Frame Rate Converter
**Version: 1.2  (September 2nd 2017)**
By Etienne Charland

Should be: **Version: 1.2.1  (May 12th 2018)**

**Comment by mysteryx93** [comment]
Correct. Fixing it.

**Comment by lecoyote418** [comment]
There is the same issue with 1.3. It shows:

> Frame Rate Converter
> Version: 1.2.1 (May 12th 2018)

**Comment by mysteryx93** [comment]
ok updated the file
