### ISSUE TITLE
How to use this with AviSynth (MPC-HC player)

### ISSUE THREAD

**Issue by hegde-atri** [mysteryx93/FrameRateConverter#2]
I'm a noob with how to set this up with what i presume as aviSynth, it'd be helpful if you could tell me how to get it working with mpc-hc or potplayer. Here is my discord hegde_atri#3808 . TYSM!!

**Comment by Tsubajashi** [comment]
did you get any information back?

**Comment by hegde-atri** [comment]
nope :/

**Comment by mysteryx93** [comment]
This is not designed to run at playback speed.

For live playback, [use SVP here](https://www.svp-team.com/).
